package singel;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbggenerated Mon Dec 25 10:16:55 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookid
     *
     * @mbggenerated Mon Dec 25 10:16:55 CST 2017
     */
    private String bookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookname
     *
     * @mbggenerated Mon Dec 25 10:16:55 CST 2017
     */
    private String bookname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbggenerated Mon Dec 25 10:16:55 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbggenerated Mon Dec 25 10:16:55 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookid
     *
     * @return the value of book.bookid
     *
     * @mbggenerated Mon Dec 25 10:16:55 CST 2017
     */
    public String getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookid
     *
     * @param bookid the value for book.bookid
     *
     * @mbggenerated Mon Dec 25 10:16:55 CST 2017
     */
    public void setBookid(String bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookname
     *
     * @return the value of book.bookname
     *
     * @mbggenerated Mon Dec 25 10:16:55 CST 2017
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookname
     *
     * @param bookname the value for book.bookname
     *
     * @mbggenerated Mon Dec 25 10:16:55 CST 2017
     */
    public void setBookname(String bookname) {
        this.bookname = bookname;
    }
}